### ISSUE TITLE
Sidekiq cook book

### ISSUE THREAD

**Issue by michaelachrisco** [westernmilling/chef-cookbooks#1]
Planning on including: https://github.com/mperham/sidekiq/tree/master/examples/chef/cookbooks/sidekiq
into the branch. Let me know if you ever get a vagrant to test with.

**Comment by josephbridgwaterrowe** [comment]
I added a sidekiq cook book some time back, do you want to take a look and give some feedback?

**Comment by michaelachrisco** [comment]
I see it here: https://github.com/westernmilling/chef-cookbooks/blob/master/site-cookbooks/deploy/files/default/sidekiq.sh

Closing :+1:
